name: ci
on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Lint
        uses: github/super-linter@v4
        env:
          SUPPRESS_POSSUM: true
          VALIDATE_CSHARP: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_ALL_CODEBASE: false

      - name: Test
        run: dotnet test sbtw.sln --logger "trx;LogFileName=TestResults-sbtw.Editor.Tests.trx"

      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-sbtw.Editor.Tests
          path: ${{ github.workspace }}/tests/sbtw.Editor.Tests/TestResults/TestResults-sbtw.Editor.Tests.trx

