name: deploy
on:
  release:
    types: [ released ]

jobs:
  pack:
    name: Pack
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - { name: Windows, runner: windows-latest, runtime: win-x64 }
          - { name: Linux, runner: ubuntu-latest, runtime: ubuntu.20.04-x64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: |
          dotnet publish ./src/desktop/sbtw.Desktop.${{ matrix.os.name }} --nologo -c Release -o ./output -r ${{ matrix.os.runtime }} --self-contained true -p:Version=${{ github.ref_name }}
          7z a -tzip sbtw-${{ matrix.os.runtime }}.zip output/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.ref_name }}-${{ matrix.os.runtime }}
          path: ${{ github.workspace }}/sbtw-${{ matrix.os.runtime }}.zip
          retention-days: 1

  deploy:
    name: Deploy
    needs: [ pack ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ 'win-x64', 'ubuntu.20.04-x64' ]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.ref_name }}-${{ matrix.runtime }}
          path: ${{ github.workspace }}

      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sbtw-${{ matrix.runtime }}.zip"
          allowUpdates: true
          tag: ${{ github.event.release.tag_name }}
